volumes:
  db_data:

services:
  app:
    image: music-api:latest
    build:
      context: .
    environment:
        DATABASE_HOST: db
        DATABASE_PORT: 3306
        DATABASE_USERNAME: vapor_username
        DATABASE_PASSWORD: vapor_password
        DATABASE_NAME: vapor_database
    depends_on:
      - db
    ports:
      - '8080:8080'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: vapor_username
      MYSQL_PASSWORD: vapor_password
      MYSQL_DATABASE: vapor_database
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3310:3306'
