name: Docker Build and Push
on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar mi repositorio
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Crear la imagen
        run: docker build -t tacod3v/music-api-411:latest .

      - name: Publicar la imagen
        run: docker push tacod3v/music-api-411:latest
